// AllDeputations India Map — Sample fixture data
// Labels any output as sample data; never connected to real vacancies.
//
// Counts: distinct vacancy LISTINGS (not posts). A multi-post ad = 1 listing.
// Multi-state listings may count in each relevant state but once nationally.
// Nationwide and unknown-location records appear in separate buckets only.

// ===== PROVIDER BOUNDARY =====
// Everything below is mock. The adapter boundary (to be built later) lives
// in js/map-provider.js and accepts the same shape from enriched vacancy records.

export const SCENARIO = "populated"; // flip to "empty" for all-zero testing

export const EXCHANGES = [
  { id: "all",       label: "All Deputations",         icon: "briefcase",  available: true  },
  { id: "govt",      label: "Government Deputations",  icon: "building-2", available: true  },
  { id: "private",   label: "Private Deputations",     icon: "building",   available: true  },
  { id: "internship",label: "Internship Exchange",     icon: "graduation", available: true  },
  { id: "manpower",  label: "Manpower Exchange",       icon: "users",      available: true  },
  { id: "campus",    label: "Campus Recruitment",      icon: "landmark",   available: false },
  { id: "entrance",  label: "Entrance Exam",           icon: "book-open",  available: false }
];

// Functional categories used in the Pune results view
export const FUNCTIONS = [
  "Show all functional jobs",
  "Executive & Leadership",
  "Information Technology (IT)",
  "Marketing & Communications",
  "Operations & Supply Chain",
  "Sales & Business Development"
];

// Filter options
export const FILTERS = {
  qualification: ["Any", "10th Pass", "12th Pass", "Graduate", "Post Graduate", "Doctorate"],
  experience:   ["Any", "0-1 years", "1-3 years", "3-5 years", "5-10 years", "10+ years"],
  jobType:      ["Any", "Full-time", "Part-time", "Contract", "Temporary"],
  jobTime:      ["Any", "Day Shift", "Night Shift", "Flexible"],
  jobShift:     ["Any", "On-site", "Remote", "Hybrid"]
};

// Helper: stable listing ID
let _id = 1;
const nextId = () => `LIST-${String(_id++).padStart(3,'0')}`;

export const POPULATED_LISTINGS = [
  // ===== MAHARASHTRA (MH) — 12 listings, 8 districts =====
  { id: nextId(), title: "Section Officer – Pune Division", state: "MH", district: "Pune", city: "Pune",
    category: "govt", function: "Executive & Leadership", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "3-5 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-10-15", active: true },
  { id: nextId(), title: "Assistant Director – Mumbai", state: "MH", district: "Mumbai City", city: "Mumbai",
    category: "govt", function: "Executive & Leadership", qualification: "Post Graduate", qualificationGroup: "Post Graduate (General)", experience: "5-10 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-11-01", active: true },
  { id: nextId(), title: "Software Engineer – Nagpur IT Cell", state: "MH", district: "Nagpur", city: "Nagpur",
    category: "private", function: "Information Technology (IT)", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "1-3 years",
    jobType: "Full-time", jobTime: "Flexible", jobShift: "Remote",
    posts: 1, closingDate: "2026-09-30", active: true },
  { id: nextId(), title: "Marketing Manager – Thane", state: "MH", district: "Thane", city: "Thane",
    category: "private", function: "Marketing & Communications", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "3-5 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "Hybrid",
    posts: 2, closingDate: "2026-10-20", active: true },
  { id: nextId(), title: "Supply Chain Analyst – Pune", state: "MH", district: "Pune", city: "Pune",
    category: "private", function: "Operations & Supply Chain", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "1-3 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-11-15", active: true },
  { id: nextId(), title: "Sales Executive – Mumbai", state: "MH", district: "Mumbai Suburban", city: "Mumbai",
    category: "private", function: "Sales & Business Development", qualification: "12th Pass", qualificationGroup: "12th Pass", experience: "0-1 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-10-05", active: true },
  { id: nextId(), title: "Research Scientist – Nashik", state: "MH", district: "Nashik", city: "Nashik",
    category: "govt", function: "Information Technology (IT)", qualification: "Post Graduate", qualificationGroup: "Post Graduate (General)", experience: "5-10 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-11-25", active: true },
  { id: nextId(), title: "HR Executive – Aurangabad", state: "MH", district: "Aurangabad", city: "Aurangabad",
    category: "private", function: "Executive & Leadership", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "2-4 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-10-30", active: true },
  { id: nextId(), title: "Data Scientist – Kolhapur", state: "MH", district: "Kolhapur", city: "Kolhapur",
    category: "private", function: "Information Technology (IT)", qualification: "Post Graduate", qualificationGroup: "Post Graduate (General)", experience: "3-5 years",
    jobType: "Full-time", jobTime: "Flexible", jobShift: "Remote",
    posts: 1, closingDate: "2026-12-01", active: true },
  { id: nextId(), title: "Field Officer – Solapur", state: "MH", district: "Solapur", city: "Solapur",
    category: "govt", function: "Operations & Supply Chain", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "1-3 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-10-12", active: true },
  { id: nextId(), title: "Accounts Clerk – Sangli", state: "MH", district: "Sangli", city: "Sangli",
    category: "govt", function: "Executive & Leadership", qualification: "12th Pass", qualificationGroup: "12th Pass", experience: "0-1 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-11-08", active: true },
  { id: nextId(), title: "Quality Engineer – Ahmednagar", state: "MH", district: "Ahmednagar", city: "Ahmednagar",
    category: "private", function: "Operations & Supply Chain", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "3-5 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-10-22", active: true },

  // ===== DELHI (DL) — 5 listings =====
  { id: nextId(), title: "Deputation Officer – Central Secretariat", state: "DL", district: "New Delhi", city: "New Delhi",
    category: "govt", function: "Executive & Leadership", qualification: "Post Graduate", qualificationGroup: "Post Graduate (General)", experience: "5-10 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-11-20", active: true },
  { id: nextId(), title: "Data Analyst – Delhi Govt", state: "DL", district: "New Delhi", city: "New Delhi",
    category: "govt", function: "Information Technology (IT)", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "1-3 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-10-10", active: true },
  { id: nextId(), title: "Policy Advisor – Central Delhi", state: "DL", district: "Central Delhi", city: "Central Delhi",
    category: "govt", function: "Executive & Leadership", qualification: "Post Graduate", qualificationGroup: "Post Graduate (General)", experience: "10+ years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-12-05", active: true },
  { id: nextId(), title: "Urban Planner – Delhi Development Authority", state: "DL", district: "South East Delhi", city: "South East Delhi",
    category: "govt", function: "Operations & Supply Chain", qualification: "Post Graduate", qualificationGroup: "Post Graduate (General)", experience: "5-10 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-11-28", active: true },
  { id: nextId(), title: "IT Auditor – Central Vigilance Commission", state: "DL", district: "New Delhi", city: "New Delhi",
    category: "govt", function: "Information Technology (IT)", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "3-5 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-10-18", active: true },

  // ===== KARNATAKA (KA) — 7 listings, 6 districts =====
  { id: nextId(), title: "Product Manager – Bengaluru", state: "KA", district: "Bengaluru Urban", city: "Bengaluru",
    category: "private", function: "Executive & Leadership", qualification: "Post Graduate", qualificationGroup: "Post Graduate (General)", experience: "5-10 years",
    jobType: "Full-time", jobTime: "Flexible", jobShift: "Hybrid",
    posts: 1, closingDate: "2026-11-30", active: true },
  { id: nextId(), title: "DevOps Engineer – Mysuru", state: "KA", district: "Mysuru", city: "Mysuru",
    category: "private", function: "Information Technology (IT)", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "3-5 years",
    jobType: "Full-time", jobTime: "Flexible", jobShift: "Remote",
    posts: 1, closingDate: "2026-12-10", active: true },
  { id: nextId(), title: "Marketing Lead – Mangaluru", state: "KA", district: "Dakshina Kannada", city: "Mangaluru",
    category: "private", function: "Marketing & Communications", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "2-4 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-10-25", active: true },
  { id: nextId(), title: "Research Fellow – Hubli", state: "KA", district: "Dharwad", city: "Hubballi-Dharwad",
    category: "govt", function: "Executive & Leadership", qualification: "Post Graduate", qualificationGroup: "Post Graduate (General)", experience: "1-3 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-11-12", active: true },
  { id: nextId(), title: "Supply Chain Lead – Belagavi", state: "KA", district: "Belagavi", city: "Belagavi",
    category: "private", function: "Operations & Supply Chain", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "3-5 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "Hybrid",
    posts: 1, closingDate: "2026-12-01", active: true },
  { id: nextId(), title: "Civil Engineer – Kalaburagi", state: "KA", district: "Kalaburagi", city: "Kalaburagi",
    category: "govt", function: "Operations & Supply Chain", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "3-5 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-10-28", active: true },
  { id: nextId(), title: "Content Strategist – Shivamogga", state: "KA", district: "Shivamogga", city: "Shivamogga",
    category: "private", function: "Marketing & Communications", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "1-3 years",
    jobType: "Full-time", jobTime: "Flexible", jobShift: "Remote",
    posts: 1, closingDate: "2026-11-05", active: true },

  // ===== TAMIL NADU (TN) — 7 listings, 6 districts =====
  { id: nextId(), title: "Intern – Chennai Development", state: "TN", district: "Chennai", city: "Chennai",
    category: "internship", function: "Operations & Supply Chain", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "0-1 years",
    jobType: "Part-time", jobTime: "Flexible", jobShift: "Remote",
    posts: 1, closingDate: "2026-09-25", active: true },
  { id: nextId(), title: "Software Architect – Coimbatore", state: "TN", district: "Coimbatore", city: "Coimbatore",
    category: "private", function: "Information Technology (IT)", qualification: "Post Graduate", qualificationGroup: "Post Graduate (General)", experience: "8-12 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "Hybrid",
    posts: 1, closingDate: "2026-12-15", active: true },
  { id: nextId(), title: "Textile Engineer – Tiruppur", state: "TN", district: "Tiruppur", city: "Tiruppur",
    category: "private", function: "Operations & Supply Chain", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "3-5 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-11-08", active: true },
  { id: nextId(), title: "District Collector – Madurai", state: "TN", district: "Madurai", city: "Madurai",
    category: "govt", function: "Executive & Leadership", qualification: "Post Graduate", qualificationGroup: "Post Graduate (General)", experience: "5-10 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-12-20", active: true },
  { id: nextId(), title: "Auto Components QA – Salem", state: "TN", district: "Salem", city: "Salem",
    category: "private", function: "Operations & Supply Chain", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "2-4 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-10-30", active: true },
  { id: nextId(), title: "Port Logistics Officer – Thoothukudi", state: "TN", district: "Thoothukudi", city: "Thoothukudi",
    category: "govt", function: "Executive & Leadership", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "3-5 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-11-15", active: true },
  { id: nextId(), title: "Agri-Tech Intern – Thanjavur", state: "TN", district: "Thanjavur", city: "Thanjavur",
    category: "internship", function: "Operations & Supply Chain", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "0-1 years",
    jobType: "Part-time", jobTime: "Flexible", jobShift: "Remote",
    posts: 1, closingDate: "2026-09-28", active: true },

  // ===== UTTAR PRADESH (UP) — 8 listings, 7 districts =====
  { id: nextId(), title: "Block Development Officer – Lucknow", state: "UP", district: "Lucknow", city: "Lucknow",
    category: "govt", function: "Executive & Leadership", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "3-5 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-10-25", active: true },
  { id: nextId(), title: "Handloom Designer – Varanasi", state: "UP", district: "Varanasi", city: "Varanasi",
    category: "private", function: "Marketing & Communications", qualification: "12th Pass", qualificationGroup: "12th Pass", experience: "1-3 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-11-10", active: true },
  { id: nextId(), title: "Leather Technologist – Kanpur", state: "UP", district: "Kanpur Nagar", city: "Kanpur",
    category: "private", function: "Operations & Supply Chain", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "3-5 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-12-05", active: true },
  { id: nextId(), title: "Public Health Officer – Agra", state: "UP", district: "Agra", city: "Agra",
    category: "govt", function: "Executive & Leadership", qualification: "Post Graduate", qualificationGroup: "Post Graduate (General)", experience: "5-10 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-11-28", active: true },
  { id: nextId(), title: "Sugar Mill Engineer – Meerut", state: "UP", district: "Meerut", city: "Meerut",
    category: "private", function: "Information Technology (IT)", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "2-4 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-10-18", active: true },
  { id: nextId(), title: "Sugarcane Researcher – Bahraich", state: "UP", district: "Bahraich", city: "Bahraich",
    category: "govt", function: "Executive & Leadership", qualification: "Post Graduate", qualificationGroup: "Post Graduate (General)", experience: "5-10 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-12-01", active: true },
  { id: nextId(), title: "Social Worker – Prayagraj", state: "UP", district: "Prayagraj", city: "Prayagraj",
    category: "govt", function: "Executive & Leadership", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "1-3 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-11-05", active: true },
  { id: nextId(), title: "E-Commerce Manager – Ghaziabad", state: "UP", district: "Ghaziabad", city: "Ghaziabad",
    category: "private", function: "Sales & Business Development", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "3-5 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-10-30", active: true },

  // ===== WEST BENGAL (WB) — 7 listings, 6 districts =====
  { id: nextId(), title: "Content Writer – Kolkata", state: "WB", district: "Kolkata", city: "Kolkata",
    category: "private", function: "Marketing & Communications", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "0-1 years",
    jobType: "Full-time", jobTime: "Flexible", jobShift: "Remote",
    posts: 1, closingDate: "2026-10-08", active: true },
  { id: nextId(), title: "Port Operations Manager – Haldia", state: "WB", district: "Purba Medinipur", city: "Haldia",
    category: "private", function: "Operations & Supply Chain", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "3-5 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-11-20", active: true },
  { id: nextId(), title: "Tea Estate Manager – Darjeeling", state: "WB", district: "Darjeeling", city: "Darjeeling",
    category: "private", function: "Executive & Leadership", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "5-10 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-12-08", active: true },
  { id: nextId(), title: "Jute Technology Officer – Howrah", state: "WB", district: "Howrah", city: "Howrah",
    category: "govt", function: "Information Technology (IT)", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "2-4 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-10-15", active: true },
  { id: nextId(), title: "Civic Planner – Siliguri", state: "WB", district: "Darjeeling", city: "Siliguri",
    category: "govt", function: "Executive & Leadership", qualification: "Post Graduate", qualificationGroup: "Post Graduate (General)", experience: "3-5 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-11-28", active: true },
  { id: nextId(), title: "Fisheries Officer – South 24 Parganas", state: "WB", district: "South 24 Parganas", city: "Kakdwip",
    category: "govt", function: "Operations & Supply Chain", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "1-3 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-10-20", active: true },
  { id: nextId(), title: "Steel Works Engineer – Asansol", state: "WB", district: "Paschim Bardhaman", city: "Asansol",
    category: "private", function: "Information Technology (IT)", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "3-5 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-12-12", active: true },

  // ===== GUJARAT (GJ) — 7 listings, 6 districts =====
  { id: nextId(), title: "Industrial Engineer – Ahmedabad", state: "GJ", district: "Ahmedabad", city: "Ahmedabad",
    category: "private", function: "Operations & Supply Chain", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "3-5 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-11-10", active: true },
  { id: nextId(), title: "Diamond Quality Analyst – Surat", state: "GJ", district: "Surat", city: "Surat",
    category: "private", function: "Executive & Leadership", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "1-3 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-10-28", active: true },
  { id: nextId(), title: "Petrochemical Engineer – Vadodara", state: "GJ", district: "Vadodara", city: "Vadodara",
    category: "private", function: "Information Technology (IT)", qualification: "Post Graduate", qualificationGroup: "Post Graduate (General)", experience: "5-10 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-12-01", active: true },
  { id: nextId(), title: "Port Logistics Officer – Rajkot", state: "GJ", district: "Rajkot", city: "Rajkot",
    category: "govt", function: "Operations & Supply Chain", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "2-4 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-11-15", active: true },
  { id: nextId(), title: "Salt Farm Manager – Bhavnagar", state: "GJ", district: "Bhavnagar", city: "Bhavnagar",
    category: "govt", function: "Executive & Leadership", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "3-5 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-10-22", active: true },
  { id: nextId(), title: "Pharma QA Lead – Gandhinagar", state: "GJ", district: "Gandhinagar", city: "Gandhinagar",
    category: "private", function: "Operations & Supply Chain", qualification: "Post Graduate", qualificationGroup: "Post Graduate (General)", experience: "5-10 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-11-30", active: true },
  { id: nextId(), title: "Tourism Officer – Kutch", state: "GJ", district: "Kutch", city: "Bhuj",
    category: "govt", function: "Marketing & Communications", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "1-3 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-10-08", active: true },

  // ===== RAJASTHAN (RJ) — 7 listings, 6 districts =====
  { id: nextId(), title: "Tourism Officer – Jaipur", state: "RJ", district: "Jaipur", city: "Jaipur",
    category: "govt", function: "Marketing & Communications", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "1-3 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-10-18", active: true },
  { id: nextId(), title: "Mining Engineer – Jodhpur", state: "RJ", district: "Jodhpur", city: "Jodhpur",
    category: "private", function: "Operations & Supply Chain", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "3-5 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-11-05", active: true },
  { id: nextId(), title: "Heritage Conservationist – Udaipur", state: "RJ", district: "Udaipur", city: "Udaipur",
    category: "govt", function: "Executive & Leadership", qualification: "Post Graduate", qualificationGroup: "Post Graduate (General)", experience: "5-10 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-12-10", active: true },
  { id: nextId(), title: "Textile Designer – Kota", state: "RJ", district: "Kota", city: "Kota",
    category: "private", function: "Marketing & Communications", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "2-4 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-10-25", active: true },
  { id: nextId(), title: "Solar Plant Supervisor – Bikaner", state: "RJ", district: "Bikaner", city: "Bikaner",
    category: "govt", function: "Operations & Supply Chain", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "3-5 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-11-20", active: true },
  { id: nextId(), title: "Agriculture Officer – Alwar", state: "RJ", district: "Alwar", city: "Alwar",
    category: "govt", function: "Executive & Leadership", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "1-3 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-10-12", active: true },
  { id: nextId(), title: "Desert Safari Guide – Jaisalmer", state: "RJ", district: "Jaisalmer", city: "Jaisalmer",
    category: "private", function: "Marketing & Communications", qualification: "12th Pass", qualificationGroup: "12th Pass", experience: "0-1 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-11-30", active: true },

  // ===== TELANGANA (TS) — 6 listings =====
  { id: nextId(), title: "DevOps Engineer – Hyderabad", state: "TS", district: "Hyderabad", city: "Hyderabad",
    category: "private", function: "Information Technology (IT)", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "3-5 years",
    jobType: "Full-time", jobTime: "Flexible", jobShift: "Remote",
    posts: 1, closingDate: "2026-11-05", active: true },
  { id: nextId(), title: "Pharma Analyst – Warangal", state: "TS", district: "Warangal", city: "Warangal",
    category: "private", function: "Operations & Supply Chain", qualification: "Post Graduate", qualificationGroup: "Post Graduate (General)", experience: "2-4 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-10-20", active: true },
  { id: nextId(), title: "Public Prosecutor – Karimnagar", state: "TS", district: "Karimnagar", city: "Karimnagar",
    category: "govt", function: "Executive & Leadership", qualification: "Post Graduate", qualificationGroup: "Post Graduate (General)", experience: "5-10 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-12-15", active: true },
  { id: nextId(), title: "Agri-Research Fellow – Nizamabad", state: "TS", district: "Nizamabad", city: "Nizamabad",
    category: "govt", function: "Executive & Leadership", qualification: "Post Graduate", qualificationGroup: "Post Graduate (General)", experience: "1-3 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-11-10", active: true },
  { id: nextId(), title: "UX Designer – Ranga Reddy", state: "TS", district: "Ranga Reddy", city: "Hyderabad",
    category: "private", function: "Information Technology (IT)", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "2-4 years",
    jobType: "Full-time", jobTime: "Flexible", jobShift: "Hybrid",
    posts: 1, closingDate: "2026-12-01", active: true },
  { id: nextId(), title: "Youth Development Officer – Khammam", state: "TS", district: "Khammam", city: "Khammam",
    category: "govt", function: "Executive & Leadership", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "1-3 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-10-28", active: true },

  // ===== KERALA (KL) — 6 listings =====
  { id: nextId(), title: "Marine Biologist – Kochi", state: "KL", district: "Ernakulam", city: "Kochi",
    category: "govt", function: "Operations & Supply Chain", qualification: "Post Graduate", qualificationGroup: "Post Graduate (General)", experience: "5-10 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-11-22", active: true },
  { id: nextId(), title: "Ayurveda Therapist – Kozhikode", state: "KL", district: "Kozhikode", city: "Kozhikode",
    category: "private", function: "Executive & Leadership", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "1-3 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-10-15", active: true },
  { id: nextId(), title: "Spice Export Officer – Idukki", state: "KL", district: "Idukki", city: "Idukki",
    category: "govt", function: "Executive & Leadership", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "3-5 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-11-08", active: true },
  { id: nextId(), title: "Software Trainer – Thrissur", state: "KL", district: "Thrissur", city: "Thrissur",
    category: "private", function: "Information Technology (IT)", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "2-4 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-12-05", active: true },
  { id: nextId(), title: "Backwater Guide – Alleppey", state: "KL", district: "Alappuzha", city: "Alappuzha",
    category: "private", function: "Marketing & Communications", qualification: "12th Pass", qualificationGroup: "12th Pass", experience: "0-1 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-10-30", active: true },
  { id: nextId(), title: "Rubber Plantation Officer – Kottayam", state: "KL", district: "Kottayam", city: "Kottayam",
    category: "govt", function: "Operations & Supply Chain", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "3-5 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-11-18", active: true },

  // ===== ASSAM (AS) — 6 listings =====
  { id: nextId(), title: "Tea Board Officer – Guwahati", state: "AS", district: "Kamrup", city: "Guwahati",
    category: "govt", function: "Executive & Leadership", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "3-5 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-10-28", active: true },
  { id: nextId(), title: "Oil Refinery Engineer – Dibrugarh", state: "AS", district: "Dibrugarh", city: "Dibrugarh",
    category: "private", function: "Information Technology (IT)", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "3-5 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-11-15", active: true },
  { id: nextId(), title: "Wildlife Ranger – Kaziranga", state: "AS", district: "Nagaon", city: "Nagaon",
    category: "govt", function: "Executive & Leadership", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "1-3 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-10-10", active: true },
  { id: nextId(), title: "Silk Weaving Supervisor – Sivasagar", state: "AS", district: "Sivasagar", city: "Sivasagar",
    category: "govt", function: "Executive & Leadership", qualification: "12th Pass", qualificationGroup: "12th Pass", experience: "2-4 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-11-22", active: true },
  { id: nextId(), title: "Hospitality Trainee – Silchar", state: "AS", district: "Cachar", city: "Silchar",
    category: "internship", function: "Operations & Supply Chain", qualification: "12th Pass", qualificationGroup: "12th Pass", experience: "0-1 years",
    jobType: "Part-time", jobTime: "Flexible", jobShift: "On-site",
    posts: 1, closingDate: "2026-09-20", active: true },
  { id: nextId(), title: "Bridge Engineer – Tinsukia", state: "AS", district: "Tinsukia", city: "Tinsukia",
    category: "govt", function: "Operations & Supply Chain", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "5-10 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-12-01", active: true },

  // ===== MADHYA PRADESH (MP) — 6 listings, 6 districts =====
  { id: nextId(), title: "Tiger Reserve Officer – Burhanpur", state: "MP", district: "Burhanpur", city: "Burhanpur",
    category: "govt", function: "Executive & Leadership", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "3-5 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-11-05", active: true },
  { id: nextId(), title: "Cotton Trader – Barwani", state: "MP", district: "Barwani", city: "Barwani",
    category: "private", function: "Sales & Business Development", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "1-3 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-10-18", active: true },
  { id: nextId(), title: "Power Plant Engineer – Neemuch", state: "MP", district: "Neemuch", city: "Neemuch",
    category: "private", function: "Information Technology (IT)", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "3-5 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-12-10", active: true },
  { id: nextId(), title: "Irrigation Officer – Sagar", state: "MP", district: "Sagar", city: "Sagar",
    category: "govt", function: "Operations & Supply Chain", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "2-4 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-11-20", active: true },
  { id: nextId(), title: "Cement Plant Manager – Ratlam", state: "MP", district: "Ratlam", city: "Ratlam",
    category: "private", function: "Executive & Leadership", qualification: "Post Graduate", qualificationGroup: "Post Graduate (General)", experience: "5-10 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-10-30", active: true },
  { id: nextId(), title: "Tribal Welfare Officer – Jhabua", state: "MP", district: "Jhabua", city: "Jhabua",
    category: "govt", function: "Executive & Leadership", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "1-3 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-11-08", active: true },

  // ===== ODISHA (OD) — 6 listings, 6 districts =====
  { id: nextId(), title: "Port Trust Officer – Bhadrak", state: "OD", district: "Bhadrak", city: "Bhadrak",
    category: "govt", function: "Executive & Leadership", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "3-5 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-11-12", active: true },
  { id: nextId(), title: "Spice Trader – Balangir", state: "OD", district: "Balangir", city: "Balangir",
    category: "private", function: "Sales & Business Development", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "1-3 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-10-25", active: true },
  { id: nextId(), title: "Smart City Engineer – Khordha", state: "OD", district: "Khordha", city: "Bhubaneswar",
    category: "govt", function: "Information Technology (IT)", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "3-5 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-12-05", active: true },
  { id: nextId(), title: "Bauxite Mine Manager – Rayagada", state: "OD", district: "Rayagada", city: "Rayagada",
    category: "private", function: "Operations & Supply Chain", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "5-10 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-11-28", active: true },
  { id: nextId(), title: "Coastal Surveyor – Ganjam", state: "OD", district: "Ganjam", city: "Berhampur",
    category: "govt", function: "Executive & Leadership", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "2-4 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-10-15", active: true },
  { id: nextId(), title: "Cashew Export Officer – Balasore", state: "OD", district: "Balasore", city: "Balasore",
    category: "govt", function: "Executive & Leadership", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "1-3 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-11-20", active: true },

  // ===== PUNJAB (PB) — 6 listings =====
  { id: nextId(), title: "Wheat Research Scientist – Ludhiana", state: "PB", district: "Ludhiana", city: "Ludhiana",
    category: "govt", function: "Executive & Leadership", qualification: "Post Graduate", qualificationGroup: "Post Graduate (General)", experience: "5-10 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-11-15", active: true },
  { id: nextId(), title: "Dairy Technologist – Amritsar", state: "PB", district: "Amritsar", city: "Amritsar",
    category: "private", function: "Operations & Supply Chain", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "2-4 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-10-20", active: true },
  { id: nextId(), title: "Sports Coach – Jalandhar", state: "PB", district: "Jalandhar", city: "Jalandhar",
    category: "govt", function: "Executive & Leadership", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "3-5 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-12-01", active: true },
  { id: nextId(), title: "IT Support – Mohali", state: "PB", district: "Mohali", city: "Mohali",
    category: "private", function: "Information Technology (IT)", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "1-3 years",
    jobType: "Full-time", jobTime: "Flexible", jobShift: "Remote",
    posts: 1, closingDate: "2026-11-08", active: true },
  { id: nextId(), title: "Textile Designer – Patiala", state: "PB", district: "Patiala", city: "Patiala",
    category: "private", function: "Marketing & Communications", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "2-4 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-10-28", active: true },
  { id: nextId(), title: "Agricultural Extension Officer – Bathinda", state: "PB", district: "Bathinda", city: "Bathinda",
    category: "govt", function: "Executive & Leadership", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "1-3 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-11-22", active: true },

  // ===== HARYANA (HR) — 6 listings =====
  { id: nextId(), title: "Automotive Engineer – Gurugram", state: "HR", district: "Gurugram", city: "Gurugram",
    category: "private", function: "Operations & Supply Chain", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "3-5 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-11-10", active: true },
  { id: nextId(), title: "Agricultural Scientist – Hisar", state: "HR", district: "Hisar", city: "Hisar",
    category: "govt", function: "Executive & Leadership", qualification: "Post Graduate", qualificationGroup: "Post Graduate (General)", experience: "5-10 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-12-15", active: true },
  { id: nextId(), title: "IT Project Lead – Faridabad", state: "HR", district: "Faridabad", city: "Faridabad",
    category: "private", function: "Information Technology (IT)", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "5-10 years",
    jobType: "Full-time", jobTime: "Flexible", jobShift: "Hybrid",
    posts: 1, closingDate: "2026-10-30", active: true },
  { id: nextId(), title: "Dairy Farm Supervisor – Karnal", state: "HR", district: "Karnal", city: "Karnal",
    category: "private", function: "Operations & Supply Chain", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "2-4 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-11-05", active: true },
  { id: nextId(), title: "Legal Aid – Panipat", state: "HR", district: "Panipat", city: "Panipat",
    category: "govt", function: "Executive & Leadership", qualification: "Post Graduate", qualificationGroup: "Post Graduate (General)", experience: "3-5 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-10-20", active: true },
  { id: nextId(), title: "Textile Designer – Panipat", state: "HR", district: "Panipat", city: "Panipat",
    category: "private", function: "Marketing & Communications", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "1-3 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-12-01", active: true },

  // ===== JHARKHAND (JH) — 6 listings =====
  { id: nextId(), title: "Mining Safety Officer – Dhanbad", state: "JH", district: "Dhanbad", city: "Dhanbad",
    category: "govt", function: "Executive & Leadership", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "5-10 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-11-20", active: true },
  { id: nextId(), title: "Steel Plant Engineer – Bokaro", state: "JH", district: "Bokaro", city: "Bokaro",
    category: "private", function: "Information Technology (IT)", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "3-5 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-12-05", active: true },
  { id: nextId(), title: "Tribal Development Officer – Ranchi", state: "JH", district: "Ranchi", city: "Ranchi",
    category: "govt", function: "Executive & Leadership", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "3-5 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-10-28", active: true },
  { id: nextId(), title: "Forest Ranger – Jamshedpur", state: "JH", district: "East Singhbhum", city: "Jamshedpur",
    category: "govt", function: "Executive & Leadership", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "1-3 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-11-15", active: true },
  { id: nextId(), title: "Aluminium Plant QA – Latehar", state: "JH", district: "Latehar", city: "Latehar",
    category: "private", function: "Operations & Supply Chain", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "2-4 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-10-10", active: true },
  { id: nextId(), title: "Copper Smelter Operator – Singhbhum", state: "JH", district: "West Singhbhum", city: "Chaibasa",
    category: "private", function: "Operations & Supply Chain", qualification: "12th Pass", qualificationGroup: "12th Pass", experience: "0-1 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-12-01", active: true },

  // ===== CHHATTISGARH (CG) — 6 listings =====
  { id: nextId(), title: "Steel Plant Operator – Bhilai", state: "CG", district: "Durg", city: "Bhilai",
    category: "private", function: "Operations & Supply Chain", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "2-4 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-11-08", active: true },
  { id: nextId(), title: "Coal Mine Supervisor – Korba", state: "CG", district: "Korba", city: "Korba",
    category: "private", function: "Executive & Leadership", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "5-10 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-12-12", active: true },
  { id: nextId(), title: "Rice Mill Quality Analyst – Raipur", state: "CG", district: "Raipur", city: "Raipur",
    category: "private", function: "Operations & Supply Chain", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "1-3 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-10-25", active: true },
  { id: nextId(), title: "Forest Officer – Bastar", state: "CG", district: "Bastar", city: "Jagdalpur",
    category: "govt", function: "Executive & Leadership", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "3-5 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-11-20", active: true },
  { id: nextId(), title: "Tribal Welfare Officer – Bilaspur", state: "CG", district: "Bilaspur", city: "Bilaspur",
    category: "govt", function: "Executive & Leadership", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "1-3 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-10-15", active: true },
  { id: nextId(), title: "Power Grid Engineer – Rajnandgaon", state: "CG", district: "Rajnandgaon", city: "Rajnandgaon",
    category: "govt", function: "Information Technology (IT)", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "3-5 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-12-01", active: true },

  // ===== BIHAR (BR) — 6 listings =====
  { id: nextId(), title: "Handloom Weaver – Muzaffarpur", state: "BR", district: "Muzaffarpur", city: "Muzaffarpur",
    category: "private", function: "Marketing & Communications", qualification: "12th Pass", qualificationGroup: "12th Pass", experience: "0-1 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-11-10", active: true },
  { id: nextId(), title: "Agricultural Officer – Patna", state: "BR", district: "Patna", city: "Patna",
    category: "govt", function: "Executive & Leadership", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "2-4 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-12-05", active: true },
  { id: nextId(), title: "Sugarcane Supervisor – Gaya", state: "BR", district: "Gaya", city: "Gaya",
    category: "govt", function: "Operations & Supply Chain", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "1-3 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-10-20", active: true },
  { id: nextId(), title: "Food Processing Engineer – Bhagalpur", state: "BR", district: "Bhagalpur", city: "Bhagalpur",
    category: "private", function: "Operations & Supply Chain", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "3-5 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-11-25", active: true },
  { id: nextId(), title: "Block Coordinator – Darbhanga", state: "BR", district: "Darbhanga", city: "Darbhanga",
    category: "govt", function: "Executive & Leadership", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "1-3 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-10-08", active: true },
  { id: nextId(), title: "Mica Mine Inspector – Kaimur", state: "BR", district: "Kaimur", city: "Kaimur",
    category: "govt", function: "Executive & Leadership", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "3-5 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-11-30", active: true },

  // ===== JAMMU AND KASHMIR (JK) — 6 listings =====
  { id: nextId(), title: "Saffron Cultivation Officer – Pampore", state: "JK", district: "Pulwama", city: "Pampore",
    category: "govt", function: "Executive & Leadership", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "1-3 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-10-15", active: true },
  { id: nextId(), title: "Tourism Guide – Leh", state: "JK", district: "Leh", city: "Leh",
    category: "private", function: "Marketing & Communications", qualification: "12th Pass", qualificationGroup: "12th Pass", experience: "0-1 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-11-20", active: true },
  { id: nextId(), title: "Hydroelectric Engineer – Baramulla", state: "JK", district: "Baramulla", city: "Baramulla",
    category: "govt", function: "Information Technology (IT)", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "5-10 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-12-10", active: true },
  { id: nextId(), title: "Apple Orchard Manager – Shopian", state: "JK", district: "Shopian", city: "Shopian",
    category: "private", function: "Operations & Supply Chain", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "2-4 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-11-05", active: true },
  { id: nextId(), title: "Forest Officer – Bandipora", state: "JK", district: "Bandipora", city: "Bandipora",
    category: "govt", function: "Executive & Leadership", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "3-5 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-10-28", active: true },
  { id: nextId(), title: "Handicraft Designer – Srinagar", state: "JK", district: "Srinagar", city: "Srinagar",
    category: "private", function: "Marketing & Communications", qualification: "12th Pass", qualificationGroup: "12th Pass", experience: "0-1 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-11-15", active: true },

  // ===== ANDHRA PRADESH (AP) — 6 listings =====
  { id: nextId(), title: "Port Operations Manager – Visakhapatnam", state: "AP", district: "Visakhapatnam", city: "Visakhapatnam",
    category: "private", function: "Operations & Supply Chain", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "3-5 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-11-20", active: true },
  { id: nextId(), title: "Rice Research Scientist – Guntur", state: "AP", district: "Guntur", city: "Guntur",
    category: "govt", function: "Executive & Leadership", qualification: "Post Graduate", qualificationGroup: "Post Graduate (General)", experience: "5-10 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-12-05", active: true },
  { id: nextId(), title: "Temple Tourism Officer – Tirupati", state: "AP", district: "Tirupati", city: "Tirupati",
    category: "govt", function: "Marketing & Communications", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "1-3 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-10-28", active: true },
  { id: nextId(), title: "IT Park Manager – Vijayawada", state: "AP", district: "NTR", city: "Vijayawada",
    category: "private", function: "Information Technology (IT)", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "3-5 years",
    jobType: "Full-time", jobTime: "Flexible", jobShift: "Hybrid",
    posts: 1, closingDate: "2026-11-10", active: true },
  { id: nextId(), title: "Fisheries Officer – Nellore", state: "AP", district: "SPSR Nellore", city: "Nellore",
    category: "govt", function: "Executive & Leadership", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "2-4 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-10-15", active: true },
  { id: nextId(), title: "Hydrocarbon Engineer – Kakinada", state: "AP", district: "East Godavari", city: "Kakinada",
    category: "private", function: "Operations & Supply Chain", qualification: "Post Graduate", qualificationGroup: "Post Graduate (General)", experience: "5-10 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-12-20", active: true }
];

// Edge-case fixtures for completeness testing

// Multi-state listing: appears in two states but counts once nationally
export const MULTI_STATE_LISTINGS = [
  { id: nextId(), title: "Cross-State Coordinator – MH & GJ", state: "MH,GJ", district: "Pune", city: "Pune",
    category: "govt", function: "Executive & Leadership", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "3-5 years",
    jobType: "Full-time", jobTime: "Day Shift", jobShift: "On-site",
    posts: 1, closingDate: "2026-12-01", active: true }
];

// Nationwide listing: state="All India"
export const NATIONWIDE_LISTINGS = [
  { id: nextId(), title: "National Program Director", state: "All India", district: null, city: "Remote",
    category: "govt", function: "Executive & Leadership", qualification: "Post Graduate", qualificationGroup: "Post Graduate (General)", experience: "10+ years",
    jobType: "Full-time", jobTime: "Flexible", jobShift: "Remote",
    posts: 1, closingDate: "2026-12-31", active: true }
];

// Unknown state listing: no state
export const UNKNOWN_LISTINGS = [
  { id: nextId(), title: "Remote Consultant – Location TBD", state: null, district: null, city: "Remote",
    category: "private", function: "Operations & Supply Chain", qualification: "Graduate", qualificationGroup: "Graduate (General)", experience: "1-3 years",
    jobType: "Part-time", jobTime: "Flexible", jobShift: "Remote",
    posts: 1, closingDate: "2026-11-30", active: true }
];

// Zero-result state for testing
export const ZERO_STATE = "MZ";
